# Generated by Django 2.0 on 2018-12-27 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costmanagement', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Additives',
        ),
        migrations.DeleteModel(
            name='AdditivesBaseOil',
        ),
        migrations.DeleteModel(
            name='AdditivesPolymer',
        ),
        migrations.DeleteModel(
            name='AdditivesRaw',
        ),
    ]
