# Generated by Django 2.0 on 2018-12-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costmanagement', '0002_auto_20181227_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('netBlendingQtyLiter', models.FloatField()),
                ('grossVolCrosscheck', models.FloatField()),
                ('percentCrosscheck', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='AdditivesBaseOil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('qtyInPercent', models.FloatField()),
                ('qtyInLiters', models.FloatField()),
                ('density', models.FloatField()),
                ('qtyInKgs', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='AdditivesPolymer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('qtyInPercent', models.FloatField()),
                ('qtyInLiters', models.FloatField()),
                ('density', models.FloatField()),
                ('qtyInKgs', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='AdditivesRaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('importRate', models.FloatField()),
                ('addCost', models.FloatField()),
                ('total', models.FloatField()),
                ('mtToKl', models.FloatField()),
                ('usage', models.FloatField()),
                ('netCost', models.FloatField()),
            ],
        ),
    ]
