# Generated by Django 2.0 on 2018-12-27 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costmanagement', '0003_additives_additivesbaseoil_additivespolymer_additivesraw'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Additives',
        ),
        migrations.DeleteModel(
            name='AdditivesBaseOil',
        ),
        migrations.DeleteModel(
            name='AdditivesPolymer',
        ),
        migrations.DeleteModel(
            name='AdditivesRaw',
        ),
    ]
