# Generated by Django 2.0 on 2018-12-27 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costmanagement', '0004_auto_20181227_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('netBlendingQtyLiter', models.FloatField()),
                ('grossVolCrosscheck', models.FloatField()),
                ('percentCrosscheck', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='AdditivesBaseOil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('qtyInPercent', models.FloatField()),
                ('qtyInLiters', models.FloatField()),
                ('density', models.FloatField()),
                ('qtyInKgs', models.FloatField()),
                ('additive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costmanagement.Additive')),
            ],
        ),
        migrations.CreateModel(
            name='AdditivesPolymer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('qtyInPercent', models.FloatField()),
                ('qtyInLiters', models.FloatField()),
                ('density', models.FloatField()),
                ('qtyInKgs', models.FloatField()),
                ('additive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costmanagement.Additive')),
            ],
        ),
        migrations.CreateModel(
            name='AdditivesRaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('importRate', models.FloatField()),
                ('addCost', models.FloatField()),
                ('total', models.FloatField()),
                ('mtToKl', models.FloatField()),
                ('usage', models.FloatField()),
                ('netCost', models.FloatField()),
                ('additive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costmanagement.Additive')),
            ],
        ),
        migrations.CreateModel(
            name='AllAdditives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('netBlendingQtyLiter', models.FloatField()),
                ('grossVolCrosscheck', models.FloatField()),
                ('percentCrosscheck', models.FloatField()),
            ],
        ),
    ]
