# Generated by Django 2.0 on 2018-12-27 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costmanagement', '0005_additive_additivesbaseoil_additivespolymer_additivesraw_alladditives'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllAdditives',
        ),
    ]
