# Generated by Django 2.0 on 2018-12-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costmanagement', '0006_delete_alladditives'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllAdditives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('crfPrice', models.FloatField()),
                ('addCost', models.FloatField()),
                ('costPriceInLiter', models.FloatField()),
                ('density', models.FloatField()),
                ('totalCost', models.FloatField()),
            ],
        ),
    ]
