# Generated by Django 2.0 on 2018-12-27 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costmanagement', '0007_alladditives'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumption',
            name='additives',
        ),
        migrations.RemoveField(
            model_name='consumption',
            name='baseoils',
        ),
        migrations.DeleteModel(
            name='Consumption',
        ),
        migrations.DeleteModel(
            name='ConsumptionAdditive',
        ),
        migrations.DeleteModel(
            name='ConsumptionBaseOil',
        ),
    ]
