# Generated by Django 2.0 on 2018-12-28 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costmanagement', '0009_consumption_consumptionadditive_consumptionbaseoil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blending',
            name='additives',
        ),
        migrations.RemoveField(
            model_name='blending',
            name='baseoils',
        ),
        migrations.DeleteModel(
            name='Blending',
        ),
        migrations.DeleteModel(
            name='BlendingAdditive',
        ),
        migrations.DeleteModel(
            name='BlendingBaseOil',
        ),
    ]
