# Generated by Django 2.0 on 2018-12-28 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costmanagement', '0010_auto_20181228_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=255)),
                ('sae', models.CharField(max_length=255)),
                ('percentCrosscheck', models.FloatField()),
                ('perLiterCost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='BlendingAdditive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('QtyInPercent', models.FloatField()),
                ('QtyInLiters', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costmanagement.Blending')),
            ],
        ),
        migrations.CreateModel(
            name='BlendingBaseOil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('QtyInPercent', models.FloatField()),
                ('QtyInLiters', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costmanagement.Blending')),
            ],
        ),
    ]
