# Generated by Django 2.0 on 2018-12-28 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costmanagement', '0011_blending_blendingadditive_blendingbaseoil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Packing',
        ),
    ]
