# Generated by Django 2.0 on 2018-12-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costmanagement', '0012_delete_packing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('pereach', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='SnPacking',
        ),
    ]
