# Generated by Django 2.0 on 2019-01-22 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costmanagement', '0014_auto_20190122_2251'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consumption',
        ),
    ]
