# Generated by Django 2.0 on 2019-01-22 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costmanagement', '0015_delete_consumption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=255)),
                ('sae', models.CharField(max_length=255)),
                ('netBlendingQty', models.FloatField()),
                ('grossVolCrosscheck', models.FloatField()),
                ('crosscheck', models.FloatField()),
                ('perLiterCost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ConsumptionAdditive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('QtyInPercent', models.FloatField()),
                ('QtyInLiters', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costmanagement.Consumption')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumptionBaseOil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('QtyInPercent', models.FloatField()),
                ('QtyInLiters', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costmanagement.Consumption')),
            ],
        ),
    ]
