# Generated by Django 2.0 on 2019-01-22 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costmanagement', '0017_auto_20190123_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumptionAdditive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('QtyInPercent', models.FloatField()),
                ('QtyInLiters', models.FloatField()),
                ('value', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costmanagement.Consumption')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumptionBaseOil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('QtyInPercent', models.FloatField()),
                ('QtyInLiters', models.FloatField()),
                ('value', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costmanagement.Consumption')),
            ],
        ),
    ]
