# Generated by Django 2.0 on 2019-01-22 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costmanagement', '0019_remove_finalproduct_sn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalproduct',
            name='literValue',
        ),
    ]
