# Generated by Django 2.0 on 2019-01-23 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costmanagement', '0020_remove_finalproduct_litervalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additivesbaseoil',
            name='additive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costmanagement.Additive'),
        ),
        migrations.AlterField(
            model_name='additivespolymer',
            name='additive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costmanagement.Additive'),
        ),
        migrations.AlterField(
            model_name='additivesraw',
            name='additive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costmanagement.Additive'),
        ),
    ]
