# Generated by Django 2.0 on 2019-01-24 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costmanagement', '0021_auto_20190123_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumptionadditive',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costmanagement.Consumption'),
        ),
        migrations.AlterField(
            model_name='consumptionbaseoil',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costmanagement.Consumption'),
        ),
    ]
