# Generated by Django 2.0 on 2019-04-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costmanagement', '0022_auto_20190124_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='packing',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rawmaterials',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
