# Generated by Django 2.0 on 2019-04-23 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costmanagement', '0023_auto_20190416_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alladditives',
            old_name='sn',
            new_name='remarks',
        ),
    ]
