# Generated by Django 2.0 on 2019-05-17 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costmanagement', '0024_auto_20190424_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalproduct',
            name='costBlendDk',
        ),
        migrations.RemoveField(
            model_name='finalproduct',
            name='costPer200',
        ),
        migrations.RemoveField(
            model_name='finalproduct',
            name='costPerDrum',
        ),
        migrations.RemoveField(
            model_name='finalproduct',
            name='netCostExDk',
        ),
        migrations.RemoveField(
            model_name='finalproduct',
            name='perLiterCost',
        ),
        migrations.RemoveField(
            model_name='finalproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='finalproduct',
            name='sae',
        ),
        migrations.RemoveField(
            model_name='finalproduct',
            name='totalCost',
        ),
        migrations.RemoveField(
            model_name='finalproduct',
            name='totalQty',
        ),
        migrations.RemoveField(
            model_name='finalproduct',
            name='valueNet',
        ),
    ]
