# Generated by Django 2.0 on 2019-05-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costmanagement', '0025_auto_20190517_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalproduct',
            name='bottlepercase',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalproduct',
            name='bottlepereac',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalproduct',
            name='bottlesperpack',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalproduct',
            name='cartons',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalproduct',
            name='costpercase',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalproduct',
            name='dkcost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalproduct',
            name='dkexprice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalproduct',
            name='kscost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalproduct',
            name='labelpercase',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalproduct',
            name='lablepereac',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalproduct',
            name='litersperpack',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalproduct',
            name='packingsize',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='finalproduct',
            name='perlitercost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalproduct',
            name='qtyinliters',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalproduct',
            name='totalqty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalproduct',
            name='totalqtyunit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='finalproduct',
            name='totalsp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
