# Generated by Django 2.0 on 2019-05-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costmanagement', '0026_auto_20190517_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalproduct',
            name='product',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
