# Generated by Django 2.0 on 2019-05-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costmanagement', '0027_finalproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumption',
            name='totalvalue',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
