# Generated by Django 2.0 on 2019-05-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costmanagement', '0028_consumption_totalvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='packing',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
