# Generated by Django 2.0 on 2019-05-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costmanagement', '0029_packing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalproduct',
            name='bottlecappercase',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalproduct',
            name='bottlecapprice',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
