# Generated by Django 2.0 on 2019-07-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costmanagement', '0031_auto_20190707_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnConsumptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.IntegerField()),
            ],
        ),
    ]
