# Generated by Django 2.0 on 2019-07-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costmanagement', '0032_snconsumptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='packing',
            name='date',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='packing',
            name='sn',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
