# Generated by Django 2.0 on 2019-07-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costmanagement', '0033_auto_20190707_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnPacking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.IntegerField()),
            ],
        ),
    ]
