# Generated by Django 2.0 on 2019-07-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costmanagement', '0034_snpacking'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumption',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
