# Generated by Django 2.0 on 2019-08-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costmanagement', '0035_consumption_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='dkSupply',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='ksSupply',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='perLiterPrice',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='valueDk',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='valueKs',
        ),
        migrations.AddField(
            model_name='inventory',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='qty',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
