# Generated by Django 2.0 on 2019-08-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costmanagement', '0036_auto_20190826_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='sn',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
