# Generated by Django 2.0 on 2019-09-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costmanagement', '0037_auto_20190826_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalproduct',
            name='bottlecapprice',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='finalproduct',
            name='bottlepereac',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='finalproduct',
            name='cartons',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='finalproduct',
            name='lablepereac',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
