# Generated by Django 2.0 on 2019-09-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costmanagement', '0038_auto_20190910_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalproduct',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
