# Generated by Django 2.2.7 on 2020-04-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costmanagement', '0039_finalproduct_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='alladditives',
            name='approved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='packing',
            name='approved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='rawmaterials',
            name='approved',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
