# Generated by Django 2.2.7 on 2020-04-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costmanagement', '0040_auto_20200406_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumption',
            name='approved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='finalproduct',
            name='approved',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
