# Generated by Django 2.0 on 2018-11-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SnCount',
            fields=[
                ('sn', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
