# Generated by Django 2.0 on 2018-11-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeRefNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kp', models.IntegerField()),
                ('ks', models.IntegerField()),
            ],
        ),
    ]
