# Generated by Django 2.0 on 2018-11-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_traderefno'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.IntegerField()),
                ('s_company', models.CharField(max_length=255)),
                ('p_company', models.CharField(max_length=255)),
                ('s_trd', models.DateField()),
                ('p_trd', models.DateField()),
                ('s_trn', models.CharField(max_length=255)),
                ('p_trn', models.CharField(max_length=255)),
                ('s_type', models.CharField(max_length=255)),
                ('p_type', models.CharField(max_length=255)),
                ('s_product', models.CharField(max_length=255)),
                ('p_product', models.CharField(max_length=255)),
                ('s_origin', models.CharField(max_length=255)),
                ('p_origin', models.CharField(max_length=255)),
                ('s_customer', models.CharField(max_length=255)),
                ('p_supplier', models.CharField(max_length=255)),
                ('s_address', models.CharField(max_length=255)),
                ('p_address', models.CharField(max_length=255)),
                ('s_tad', models.DateField()),
                ('p_tad', models.DateField()),
                ('s_trade_status', models.CharField(max_length=255)),
                ('p_trade_status', models.CharField(max_length=255)),
                ('s_tcq', models.CharField(max_length=255)),
                ('p_tcq', models.CharField(max_length=255)),
                ('s_tolerance', models.CharField(max_length=255)),
                ('p_tolerance', models.CharField(max_length=255)),
                ('s_packing', models.CharField(max_length=255)),
                ('p_packing', models.CharField(max_length=255)),
                ('s_tuq', models.CharField(max_length=255)),
                ('p_tuq', models.CharField(max_length=255)),
                ('s_ratePMT', models.CharField(max_length=255)),
                ('p_ratePMT', models.CharField(max_length=255)),
                ('s_commissionAgent', models.CharField(max_length=255)),
                ('p_commissionAgent', models.CharField(max_length=255)),
                ('s_commissionRate', models.CharField(max_length=255)),
                ('p_commissionRate', models.CharField(max_length=255)),
                ('s_logisticProvider', models.CharField(max_length=255)),
                ('p_logisticProvider', models.CharField(max_length=255)),
                ('s_estimatedLogisticsCost', models.CharField(max_length=255)),
                ('p_estimatedLogisticsCost', models.CharField(max_length=255)),
                ('s_paymentTerm', models.CharField(max_length=255)),
                ('p_paymentTerm', models.CharField(max_length=255)),
                ('s_incoterm', models.CharField(max_length=255)),
                ('p_incoterm', models.CharField(max_length=255)),
                ('s_pod', models.CharField(max_length=255)),
                ('p_pol', models.CharField(max_length=255)),
                ('s_etd', models.DateField()),
                ('p_etd', models.DateField()),
                ('s_eta', models.DateField()),
                ('p_eta', models.DateField()),
                ('po_number', models.CharField(max_length=255)),
                ('po_date', models.DateField()),
                ('so_number', models.CharField(max_length=255)),
                ('so_date', models.DateField()),
            ],
        ),
    ]
