# Generated by Django 2.0 on 2018-11-25 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_tradeapproval'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TradeApproval',
        ),
    ]
