# Generated by Django 2.0 on 2018-11-26 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_tradeapproval'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SnCount',
        ),
        migrations.DeleteModel(
            name='TradeApproval',
        ),
        migrations.DeleteModel(
            name='TradeRefNo',
        ),
    ]
