# Generated by Django 2.0 on 2018-11-27 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20181126_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesandpurchase',
            name='trn',
        ),
        migrations.DeleteModel(
            name='SalesAndPurchase',
        ),
    ]
