# Generated by Django 2.0 on 2018-11-27 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20181128_0122'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAndFinance',
            fields=[
                ('trn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.TradeApproval')),
                ('balancePaymentFromBuyer', models.FloatField()),
                ('balPayBuyerCur', models.CharField(max_length=255)),
                ('balancePaymentToSupplier', models.FloatField()),
                ('balPaySupCur', models.CharField(max_length=255)),
                ('buyerDueDate', models.DateField()),
                ('supplierDueDate', models.DateField()),
                ('paymentReceived', models.FloatField()),
                ('payRecCur', models.CharField(max_length=255)),
                ('paymentSent', models.FloatField()),
                ('paySentCur', models.CharField(max_length=255)),
                ('s_paymentDate', models.DateField()),
                ('p_paymentDate', models.DateField()),
                ('s_balanceDue', models.FloatField()),
                ('s_balDueCur', models.CharField(max_length=255)),
                ('p_balanceDue', models.FloatField()),
                ('p_balDueCur', models.CharField(max_length=255)),
                ('s_paymentMode', models.CharField(max_length=255)),
                ('p_paymentMode', models.CharField(max_length=255)),
                ('s_paymentStatus', models.CharField(max_length=255)),
                ('p_paymentStatus', models.CharField(max_length=255)),
                ('s_logisticsPaymentDue', models.FloatField()),
                ('s_logisticPayDueCur', models.CharField(max_length=255)),
                ('p_logisticsPaymentDue', models.FloatField()),
                ('p_logisticPayDueCur', models.CharField(max_length=255)),
                ('s_logisticsCommisionDueDate', models.DateField()),
                ('p_logisticsCommisionDueDate', models.DateField()),
                ('s_agentCommissionPaid', models.FloatField()),
                ('s_agentCommPaidCur', models.CharField(max_length=255)),
                ('p_agentCommissionPaid', models.FloatField()),
                ('p_agentCommPaidCur', models.CharField(max_length=255)),
            ],
        ),
    ]
