# Generated by Django 2.0 on 2018-11-28 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20181128_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesAndPurchase',
            fields=[
                ('trn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.TradeApproval')),
                ('purchaseInvoiceDate', models.DateField()),
                ('salesInvoiceDate', models.DateField()),
                ('purchaseInvoiceNumber', models.CharField(max_length=255)),
                ('salesInvoiceNumber', models.CharField(max_length=255)),
                ('purchaseInvoiceAmount', models.FloatField()),
                ('purInvCur', models.CharField(max_length=255)),
                ('salesInvoiceAmount', models.FloatField()),
                ('salesInvCur', models.CharField(max_length=255)),
                ('purchaseCommissionAgent', models.CharField(max_length=255)),
                ('salesCommissionAgent', models.CharField(max_length=255)),
                ('purchaseCommissionAmount', models.FloatField()),
                ('purCommCur', models.CharField(max_length=255)),
                ('salesCommissionAmount', models.FloatField()),
                ('salesCommCur', models.CharField(max_length=255)),
                ('s_packingListDetails', models.CharField(max_length=255)),
                ('p_packingListDetails', models.CharField(max_length=255)),
                ('purchaseBillNumber', models.CharField(max_length=255)),
                ('salesBillNumber', models.CharField(max_length=255)),
                ('purchaseBillQty', models.FloatField()),
                ('salesBillQty', models.FloatField()),
                ('purchaseBillDate', models.DateField()),
                ('salesBillDate', models.DateField()),
                ('purchaseLogisticAgent', models.CharField(max_length=255)),
                ('salesLogisticAgent', models.CharField(max_length=255)),
                ('purchaseLogisticCost', models.FloatField()),
                ('purLogCur', models.CharField(max_length=255)),
                ('salesLogisticCost', models.CharField(max_length=255)),
                ('salesLogCur', models.CharField(max_length=255)),
                ('purchaseLiner', models.CharField(max_length=255)),
                ('salesLiner', models.CharField(max_length=255)),
                ('s_eda', models.DateField()),
                ('p_eta', models.DateField()),
                ('s_shipmentStatus', models.CharField(max_length=255)),
                ('p_shipmentStatus', models.CharField(max_length=255)),
            ],
        ),
    ]
