# Generated by Django 2.0 on 2018-11-29 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_approvdby'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kyc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('companyRegNo', models.CharField(max_length=255)),
                ('regAddress', models.CharField(max_length=255)),
                ('mailingAddress', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('fax', models.CharField(max_length=255)),
                ('person1', models.CharField(max_length=255)),
                ('designation1', models.CharField(max_length=255)),
                ('mobile1', models.CharField(max_length=255)),
                ('email1', models.CharField(max_length=255)),
                ('person2', models.CharField(max_length=255)),
                ('designation2', models.CharField(max_length=255)),
                ('mobile2', models.CharField(max_length=255)),
                ('email2', models.CharField(max_length=255)),
            ],
        ),
    ]
