# Generated by Django 2.0 on 2018-11-29 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_kyc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesandpurchase',
            name='trn',
        ),
        migrations.DeleteModel(
            name='SalesAndPurchase',
        ),
    ]
