# Generated by Django 2.0 on 2018-11-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_salesandpurchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySn',
            fields=[
                ('sn', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('balanceqty', models.FloatField()),
                ('inventoryvalue', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SaveInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.IntegerField()),
                ('entrydate', models.DateField()),
                ('godowndate', models.DateField()),
                ('trn', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('trd', models.DateField()),
                ('supplier', models.CharField(max_length=255)),
                ('qtyin', models.FloatField()),
                ('qtyout', models.FloatField()),
                ('incoterm', models.CharField(max_length=255)),
                ('expense', models.FloatField()),
                ('expenseCur', models.CharField(max_length=255)),
                ('net', models.FloatField()),
                ('netCur', models.CharField(max_length=100)),
                ('oldbalqtyvalue', models.FloatField()),
                ('balanceqty', models.FloatField()),
                ('unit', models.CharField(max_length=255)),
                ('godownlocation', models.CharField(max_length=255)),
                ('oldinventoryvalue', models.FloatField()),
                ('inventoryvalue', models.FloatField()),
            ],
        ),
    ]
