# Generated by Django 2.0 on 2018-12-03 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_prepayments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prepayments',
            name='trn',
        ),
        migrations.DeleteModel(
            name='PrePayments',
        ),
    ]
