# Generated by Django 2.0 on 2018-12-03 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20181203_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrePayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_dueDate', models.DateField(blank=True, null=True)),
                ('p_dueDate', models.DateField(blank=True, null=True)),
                ('s_advance', models.FloatField()),
                ('s_advanceCur', models.CharField(blank=True, max_length=255)),
                ('p_advance', models.FloatField()),
                ('p_advanceCur', models.CharField(blank=True, max_length=255)),
                ('s_lcNumberValue', models.CharField(max_length=255)),
                ('p_lcNumberValue', models.CharField(max_length=255)),
                ('s_lcIssuingBank', models.CharField(max_length=255)),
                ('p_lcIssuingBank', models.CharField(max_length=255)),
                ('advanceFromBuyers', models.FloatField()),
                ('advnaceBuyCur', models.CharField(blank=True, max_length=255)),
                ('advanceToSellers', models.FloatField()),
                ('advnaceSellCur', models.CharField(blank=True, max_length=255)),
                ('s_receivedDate', models.DateField(blank=True, null=True)),
                ('p_receivedDate', models.DateField(blank=True, null=True)),
                ('s_lcExpiryDate', models.DateField(blank=True, null=True)),
                ('p_lcExpiryDate', models.DateField(blank=True, null=True)),
                ('trn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.TradeApproval')),
            ],
        ),
    ]
