# Generated by Django 2.0 on 2018-12-06 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
