# Generated by Django 2.0 on 2018-12-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_snstock_stockjournal_stockno'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockjournal',
            name='stockdate',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockjournal',
            name='c_altqty1',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='stockjournal',
            name='c_altqty2',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='stockjournal',
            name='c_altqty3',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='stockjournal',
            name='c_qty1',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='stockjournal',
            name='c_qty2',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='stockjournal',
            name='c_qty3',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='stockjournal',
            name='p_altqty',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='stockjournal',
            name='p_qty',
            field=models.CharField(max_length=25),
        ),
    ]
