# Generated by Django 2.0 on 2018-12-09 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_auto_20181209_1326'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SnStock',
        ),
        migrations.DeleteModel(
            name='StockJournal',
        ),
        migrations.DeleteModel(
            name='StockNo',
        ),
    ]
