# Generated by Django 2.0 on 2018-12-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_auto_20181209_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnStock',
            fields=[
                ('sn', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='StockJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.IntegerField()),
                ('stockno', models.IntegerField()),
                ('stockdate', models.CharField(max_length=255)),
                ('c_product1', models.CharField(max_length=255)),
                ('c_qty1', models.CharField(max_length=25)),
                ('c_unit1', models.CharField(max_length=25)),
                ('c_altqty1', models.CharField(max_length=25)),
                ('c_altunit1', models.CharField(max_length=25)),
                ('c_product2', models.CharField(max_length=255)),
                ('c_qty2', models.CharField(max_length=25)),
                ('c_unit2', models.CharField(max_length=25)),
                ('c_altqty2', models.CharField(max_length=25)),
                ('c_altunit2', models.CharField(max_length=25)),
                ('c_product3', models.CharField(max_length=255)),
                ('c_qty3', models.CharField(max_length=25)),
                ('c_unit3', models.CharField(max_length=25)),
                ('c_altqty3', models.CharField(max_length=25)),
                ('c_altunit3', models.CharField(max_length=25)),
                ('p_product', models.CharField(max_length=255)),
                ('p_qty', models.CharField(max_length=25)),
                ('p_unit', models.CharField(max_length=25)),
                ('p_altqty', models.CharField(max_length=25)),
                ('p_altunit', models.CharField(max_length=25)),
                ('warehouse', models.CharField(max_length=255)),
                ('purpose', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StockNo',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
