# Generated by Django 2.0 on 2018-12-19 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_auto_20181219_1337'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SnCount',
        ),
    ]
