# Generated by Django 2.0 on 2018-12-20 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_auto_20181220_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrePayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dueDate', models.CharField(max_length=255)),
                ('advance', models.FloatField()),
                ('lcNumberValue', models.CharField(max_length=255)),
                ('lcIssuingBank', models.CharField(max_length=255)),
                ('advanceFromBuyers', models.FloatField()),
                ('advanceToSellers', models.FloatField()),
                ('receivedDate', models.CharField(max_length=255)),
                ('paidDate', models.CharField(max_length=255)),
                ('lcExpiryDate', models.CharField(max_length=255)),
                ('trn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.TradeApproval')),
            ],
        ),
    ]
