# Generated by Django 2.0 on 2018-12-20 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0062_prepayments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesandpurchase',
            name='trn',
        ),
        migrations.DeleteModel(
            name='SalesAndPurchase',
        ),
    ]
