# Generated by Django 2.0 on 2018-12-20 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0063_auto_20181220_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesAndPurchase',
            fields=[
                ('trn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.TradeApproval')),
                ('invoiceDate', models.CharField(blank=True, max_length=255, null=True)),
                ('invoiceNumber', models.CharField(max_length=255)),
                ('invoiceAmount', models.FloatField()),
                ('commissionAgent', models.CharField(max_length=255)),
                ('commissionAmount', models.FloatField()),
                ('packingListDetails', models.CharField(max_length=255)),
                ('billNumber', models.CharField(max_length=255)),
                ('billQty', models.FloatField()),
                ('billDate', models.CharField(blank=True, max_length=255, null=True)),
                ('logisticAgent', models.CharField(max_length=255)),
                ('logisticCost', models.FloatField()),
                ('liner', models.CharField(max_length=255)),
                ('eta', models.CharField(blank=True, max_length=255, null=True)),
                ('shipmentStatus', models.CharField(max_length=255)),
            ],
        ),
    ]
