# Generated by Django 2.0 on 2018-12-20 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0064_salesandpurchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentandfinance',
            name='trn',
        ),
        migrations.DeleteModel(
            name='PaymentAndFinance',
        ),
    ]
