# Generated by Django 2.0 on 2018-12-29 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0068_auto_20181223_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pl',
            name='trn',
        ),
        migrations.DeleteModel(
            name='PL',
        ),
    ]
