# Generated by Django 2.0 on 2018-12-29 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0069_auto_20181229_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='PL',
            fields=[
                ('trn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.TradeApproval')),
                ('p_trn', models.CharField(max_length=255)),
                ('s_purchaseTotalCost', models.FloatField()),
                ('p_purchaseTotalCost', models.FloatField()),
                ('totalRevenueFromSales', models.FloatField()),
                ('grossProfit', models.FloatField()),
                ('profitPerDrum', models.FloatField()),
            ],
        ),
    ]
