# Generated by Django 2.0 on 2018-12-29 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0071_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
