# Generated by Django 2.0 on 2018-12-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0073_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTrace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('tcq', models.FloatField(null=True)),
                ('tuq', models.FloatField(null=True)),
                ('tbq', models.FloatField(null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ('-logdate',)},
        ),
    ]
