# Generated by Django 2.0 on 2019-01-04 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0076_auto_20190104_1616'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
