# Generated by Django 2.0 on 2019-01-04 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0077_delete_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disputes',
            name='trn',
        ),
        migrations.RemoveField(
            model_name='extracost',
            name='trn',
        ),
        migrations.DeleteModel(
            name='InventorySn',
        ),
        migrations.DeleteModel(
            name='Kyc',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.RemoveField(
            model_name='paymentandfinance',
            name='trn',
        ),
        migrations.RemoveField(
            model_name='pl',
            name='trn',
        ),
        migrations.RemoveField(
            model_name='prepayments',
            name='trn',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='ProductTrace',
        ),
        migrations.RemoveField(
            model_name='salesandpurchase',
            name='trn',
        ),
        migrations.DeleteModel(
            name='SaveInventory',
        ),
        migrations.DeleteModel(
            name='SnCount',
        ),
        migrations.DeleteModel(
            name='SnStock',
        ),
        migrations.DeleteModel(
            name='StockJournal',
        ),
        migrations.DeleteModel(
            name='StockNo',
        ),
        migrations.DeleteModel(
            name='TradeRefNo',
        ),
        migrations.DeleteModel(
            name='Disputes',
        ),
        migrations.DeleteModel(
            name='ExtraCost',
        ),
        migrations.DeleteModel(
            name='PaymentAndFinance',
        ),
        migrations.DeleteModel(
            name='PL',
        ),
        migrations.DeleteModel(
            name='PrePayments',
        ),
        migrations.DeleteModel(
            name='SalesAndPurchase',
        ),
        migrations.DeleteModel(
            name='TradeApproval',
        ),
    ]
