# Generated by Django 2.0 on 2019-01-12 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0079_auto_20190104_1651'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductTrace',
        ),
    ]
