# Generated by Django 2.0 on 2019-01-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0080_delete_producttrace'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseProductTrace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('tcq', models.FloatField(null=True)),
                ('tuq', models.FloatField(null=True)),
                ('tbq', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesProductTrace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('tcq', models.FloatField(null=True)),
                ('tuq', models.FloatField(null=True)),
                ('tbq', models.FloatField(null=True)),
            ],
        ),
    ]
