# Generated by Django 2.0 on 2019-01-13 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0083_auto_20190113_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAndFinance',
            fields=[
                ('trn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.TradeApproval')),
                ('balancePayment', models.FloatField(blank=True, null=True)),
                ('dueDate', models.CharField(blank=True, max_length=255, null=True)),
                ('payment', models.FloatField(blank=True, null=True)),
                ('paymentDate', models.CharField(blank=True, max_length=255, null=True)),
                ('balanceDue', models.FloatField(blank=True, null=True)),
                ('paymentMode', models.CharField(max_length=255)),
                ('paymentStatus', models.CharField(max_length=255)),
                ('logisticsPaymentDue', models.FloatField(blank=True, null=True)),
                ('logisticsProvider', models.CharField(max_length=255)),
                ('commissionAgent', models.CharField(max_length=255)),
                ('logisticsCommissionDueDate', models.CharField(blank=True, max_length=255, null=True)),
                ('agentCommissionDueDate', models.CharField(blank=True, max_length=255, null=True)),
                ('agentCommissionPaid', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
