# Generated by Django 2.0 on 2019-01-21 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0084_paymentandfinance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
