# Generated by Django 2.0 on 2019-01-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0085_delete_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('balanceqty', models.FloatField()),
                ('unit', models.CharField(max_length=100)),
                ('inventoryvalue', models.FloatField()),
                ('inventoryrate', models.FloatField()),
            ],
        ),
    ]
