# Generated by Django 2.0 on 2019-01-21 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0086_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaveInventory',
        ),
    ]
