# Generated by Django 2.0 on 2019-01-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0087_delete_saveinventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.IntegerField()),
                ('entrydate', models.CharField(max_length=255)),
                ('godowndate', models.CharField(max_length=255)),
                ('trn', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('trd', models.CharField(max_length=255)),
                ('supplier', models.CharField(max_length=255)),
                ('qtyin', models.FloatField()),
                ('qtyout', models.FloatField()),
                ('incoterm', models.CharField(max_length=255)),
                ('expense', models.FloatField()),
                ('net', models.FloatField()),
                ('oldbalqtyvalue', models.FloatField()),
                ('balanceqty', models.FloatField()),
                ('unit', models.CharField(max_length=255)),
                ('godownlocation', models.CharField(max_length=255)),
                ('oldinventoryvalue', models.FloatField()),
                ('inventoryvalue', models.FloatField()),
                ('currentinventoryrate', models.FloatField()),
            ],
        ),
    ]
