# Generated by Django 2.0 on 2019-02-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0088_saveinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='accountNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='banker',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='swiftCode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
