# Generated by Django 2.0 on 2019-04-23 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0090_tradeapproval_baseproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traderefno',
            old_name='ks',
            new_name='sl',
        ),
    ]
