# Generated by Django 2.0 on 2019-04-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0091_auto_20190423_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepayments',
            name='nextShipmentDate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
