# Generated by Django 2.0 on 2019-05-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0092_prepayments_nextshipmentdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracost',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentandfinance',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pl',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prepayments',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salesandpurchase',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
