# Generated by Django 2.0 on 2019-05-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0093_auto_20190513_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesandpurchase',
            name='reviewed',
            field=models.NullBooleanField(),
        ),
    ]
