# Generated by Django 2.0 on 2019-06-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0094_salesandpurchase_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='approve1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kyc',
            name='approve2',
            field=models.BooleanField(default=False),
        ),
    ]
