# Generated by Django 2.0 on 2019-07-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0095_auto_20190623_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeapproval',
            name='account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tradeapproval',
            name='bank',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tradeapproval',
            name='swift',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
