# Generated by Django 2.0 on 2019-08-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0096_auto_20190709_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseproducttrace',
            name='first_trn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salesproducttrace',
            name='first_trn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
