# Generated by Django 2.0 on 2019-09-05 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0097_auto_20190822_2352'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockJournal',
        ),
    ]
