# Generated by Django 2.0 on 2019-09-05 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0098_delete_stockjournal'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdditive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('qtykg', models.FloatField()),
                ('density', models.FloatField()),
                ('qtyliter', models.FloatField()),
                ('ratekg', models.FloatField()),
                ('valuekg', models.FloatField()),
                ('rateliter', models.FloatField()),
                ('valueliter', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StockConsumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('qty', models.FloatField()),
                ('unit', models.CharField(max_length=255)),
                ('rate', models.FloatField()),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StockJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockno', models.IntegerField()),
                ('stockdate', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('qty', models.FloatField()),
                ('unit', models.CharField(max_length=255)),
                ('value', models.FloatField()),
                ('rate', models.FloatField()),
                ('production_remarks', models.CharField(max_length=255)),
                ('consumption_remarks', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StockPacking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('qty', models.FloatField()),
                ('unit', models.CharField(max_length=255)),
                ('rate', models.FloatField()),
                ('value', models.FloatField()),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.StockJournal')),
            ],
        ),
        migrations.CreateModel(
            name='StockRaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('qtykg', models.FloatField()),
                ('density', models.FloatField()),
                ('qtyliter', models.FloatField()),
                ('ratekg', models.FloatField()),
                ('valuekg', models.FloatField()),
                ('rateliter', models.FloatField()),
                ('valueliter', models.FloatField()),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.StockJournal')),
            ],
        ),
        migrations.AddField(
            model_name='stockconsumption',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.StockJournal'),
        ),
        migrations.AddField(
            model_name='stockadditive',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.StockJournal'),
        ),
    ]
