# Generated by Django 2.2.7 on 2019-11-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0100_auto_20191116_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disputes',
            name='remark',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='extracost',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentandfinance',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pl',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prepayments',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesandpurchase',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
